seeds:
  torch_seeds: [950148, 171376, 620516,
                952498, 528800, 382510,
                685351, 910227, 881256,
                160444]
  numpy_seeds: [700112, 118184, 721042,
                849212, 447234, 640394,
                471836, 792048, 194291,
                503440]
expers:
  # first experiment is 3 layers
  4_layer_dipol_gvae:
    type: "DiPol_GraphVAE"
    encoder:
      embed_rgcn_layer_params: [[128, 64], 0.0]
      pool_rgcn_layer_params: [[0.90, 0.75], 0.0]
      embed_block_layer_params: [[16, 16], 0.0]
      pool_block_layer_params: [[0.50, 0.25], 0.0]
      ff_layer_params: [[64, 16], 0.0] 
    decoder:
      embed_rgcn_layer_params: [[128, 64], 0.0]
      pool_rgcn_layer_params: [[0.90, 0.75], 0.0]
      embed_block_layer_params: [[16, 16], 0.0]
      pool_block_layer_params: [[0.50, 0.25], 0.0]
      ff_layer_params: [[64, 16], 0.0] 
