seeds:
  torch_seeds: [950148, 171376, 620516,
                952498, 528800, 382510,
                685351, 910227, 881256,
                160444]
  numpy_seeds: [700112, 118184, 721042,
                849212, 447234, 640394,
                471836, 792048, 194291,
                503440]
exper:
  # first experiment is 3 layers
  type: "DiPol_GraphVAE":
  encoder:
    embed_rgcn_layer_hidden_dims: [128, 64]
    embed_layer_hidden_dims: [16, 16, 16]
    pool_layer_downsample_percents: [0.75, 0.50, 0.25] 
    ff_layer_hidden_dims: [64, 16] 
  decoder:
    embed_rgcn_layer_hidden_dims: [128, 64]
    embed_layer_hidden_dims: [16, 16, 16]
    pool_layer_downsample_percents: [0.75, 0.50, 0.25] 
    ff_layer_hidden_dims: [64, 16] 
